# Generated by Django 6.0.6 on 2026-07-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='card_details',
            field=models.CharField(blank=True, default='Visa ending in 4242', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expiry_warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='offer_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(blank=True, default='Credit Card', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_opted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
